OPENAI_API_KEY = "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"
MODEL_NAME = "gpt-3.5-turbo"
MAX_TOKENS = 500
TEMPERATURE = 0.7
ENABLE_VOICE = false
